baseURL = "https://millmint.net"
languageCode = "en"
title = "MillMint"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

[build]
writeStats = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
sitetag = "sitetag"
characters ="characters"
sectionPagesMenu = 'main'

[outputs]
home = ["HTML", "RSS", "JSON"]