baseURL = "https://millmint.net"
languageCode = "en"
title = "MillMint"
theme = "monochrome-v1.01"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true

[build]
writeStats = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
sitetag = "sitetag"


[outputs]
home = ["HTML", "RSS", "JSON"]