baseURL = "https://millmint.net"
languageCode = "en"
title = "MillMint"
theme = "monochrome-v9.2"
defaultContentLanguage = "en"
enableEmoji = true

[build]
writeStats = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]