navbarTitle = 'MillMint'
footer = "Copyright © 2017-2021 Studio MillMint"

enableZoomingJS = true
enableTOC = true
enableSiteSearch = true
enableMathJax = false

# Codeblock
usePrismJS = false
enablePrismJSLineNo = true
enableCodeCopy = true

# SEO
enableOpenGraph = true
enableTwitterCards = true
author = "Hobart Phillips"

# Collapsible Menu
enableCollapsibleTOC = true
enableCollapsibleChangelogs = true

# Number of posts
paginate = 20

# Search
search = true
