navbarTitle = 'MillMint'
footer = "Copyright © 2017-2022 Studio MillMint"
author = "Hobart Phillips"

enable_zooming_js = true
enable_toc = true
enable_site_search = true
enable_math = false

# SEO
enable_open_graph = true
enable_twitter_cards = true

# Collapsible Menu
enable_collapsible_toc = false
enable_collapsible_changelogs = true

[list_layout]
enable_group_by_year = true
enable_show_date = false
enable_pagination = false
