[[navbar]]
  identifier = "intro"
  name = "Intro"
  url = "/intro/"
  pre = "📔"
  weight = 1
[[navbar]]
  identifier = "utopia"
  name = "Utopia"
  pre = "📓"
  url = "/utopia/"
  weight = 2
  [[navbar]]
    identifier = "vekllei"
    name = "Home"
    pre = "🏠"
    url = "/utopia/vekllei/"
    parent = "utopia"
    weight = 1
  [[navbar]]
    identifier = "characters"
    name = "Characters"
    pre = "🎎"
    url = "/utopia/characters/"
    parent = "utopia"
    weight = 2
  [[navbar]]
    identifier = "culture"
    name = "Culture"
    pre = "🏵"
    url = "/utopia/culture"
    parent = "utopia"
    weight = 3
    [[navbar]]
      identifier = "language"
      name = "Language"
      pre = "📖"
      url = "/utopia/culture/language"
      parent = "culture"
      weight = 1
    [[navbar]]
      identifier = "metaphysics"
      name = "Metaphysics"
      pre = "🪬"
      url = "/utopia/culture/metaphysics"
      parent = "culture"
      weight = 2
    [[navbar]]
      identifier = "religion"
      name = "Religion"
      pre = "💀"
      url = "/utopia/culture/religion"
      parent = "culture"
      weight = 3
    [[navbar]]
      identifier = "sagas"
      name = "Sagas"
      pre = "🕯️"
      url = "/utopia/culture/sagas"
      parent = "culture"
      weight = 4
  [[navbar]]
    identifier = "landscape"
    name = "Landscape"
    pre = "🌿"
    parent = "utopia"
    url = "/utopia/landscape"
    weight = 4
    [[navbar]]
      identifier = "boroughs"
      name = "Boroughs"
      pre = "🌐"
      url = "/utopia/landscape/boroughs"
      parent = "landscape"
      weight = 1
  [[navbar]]
    identifier = "society"
    name = "Society"
    pre = "🏛"
    parent = "utopia"
    url = "/utopia/society"
    weight = 5
    [[navbar]]
      identifier = "state"
      name = "State"
      pre = "🌸"
      url = "/utopia/society/state/"
      parent = "society"
      weight = 1
    [[navbar]]
      identifier = "industry"
      name = "Industry"
      pre = "⚙️"
      url = "/utopia/society/industry/"
      parent = "society"
      weight = 2
    [[navbar]]
    identifier = "technology"
    name = "Technology"
    pre = "🧪"
    url = "/utopia/society/technology"
    parent = "society"
    weight = 3
[[navbar]]
  identifier = "newsdesk"
  name = "MillMint"
  pre = "📕"
  url = "/millmint/"
  weight = 3
  [[navbar]]
    identifier = "about"
    name = "About"
    pre = "🌐"
    url = "/millmint/about"
    parent = "newsdesk"
    weight = 1
  [[navbar]]
    identifier = "dolls"
    name = "Dolls"
    pre = "🧍‍♀️"
    url = "/millmint/dolls/"
    parent = "newsdesk"
    weight = 2
  [[navbar]]
    identifier = "blog"
    name = "Blog"
    pre = "💬"
    url = "/millmint/blog"
    parent = "newsdesk"
    weight = 3
  [[navbar]]
    identifier = "essays"
    name = "Essays"
    pre = "📄"
    url = "/millmint/essays"
    parent = "newsdesk"
    weight = 4
    [[navbar]]
      identifier = "ghibli"
      name = "A Universal Nostalgia"
      pre = "🫧"
      url = "/millmint/essays/ghibli"
      parent = "essays"
      weight = 1
    [[navbar]]
      identifier = "utopie"
      name = "Utopie Concrete"
      pre = "☕️"
      url = "/millmint/essays/utopie"
      parent = "essays"
      weight = 2
    [[navbar]]
      identifier = "hong kong"
      name = "Not Long in Hong Kong"
      pre = "☂️"
      url = "/millmint/essays/hongkong"
      parent = "essays"
      weight = 3
    [[navbar]]
      identifier = "tokyo"
      name = "A Cashless Tokyo"
      pre = "🍜"
      url = "/millmint/essays/tokyo"
      parent = "essays"
      weight = 4
[[navbar]]
  identifier = "posts"
  name = "Stories"
  pre = "📗"
  url = "/stories/"
  weight = 4