[[navbar]]
  identifier = "intro"
  name = "Intro"
  url = "/intro/"
  pre = "📔"
  weight = 1
[[navbar]]
  identifier = "factbook"
  name = "Factbook"
  pre = "📓"
  url = "/factbook/"
  weight = 2
    [[navbar]]
    identifier = "map"
    name = "Map"
    pre = "🗺️"
    url = "/factbook/map/"
    parent = "factbook"
    weight = 1
  [[navbar]]
    identifier = "vekllei"
    name = "Vekllei"
    pre = "🌹"
    url = "/factbook/vekllei/"
    parent = "factbook"
    weight = 2
  [[navbar]]
    identifier = "bulletin"
    name = "Bulletin"
    pre = "🧾"
    url = "/factbook/bulletin/"
    parent = "factbook"
    weight = 3
  [[navbar]]
    identifier = "culture"
    name = "Culture"
    pre = "🏵"
    url = "/factbook/society/culture"
    parent = "factbook"
    weight = 4
    [[navbar]]
      identifier = "language"
      name = "Language"
      pre = "📖"
      url = "/factbook/society/culture/language"
      parent = "culture"
      weight = 1
    [[navbar]]
      identifier = "metaphysics"
      name = "Metaphysics"
      pre = "🪬"
      url = "/factbook/society/culture/metaphysics"
      parent = "culture"
      weight = 2
    [[navbar]]
      identifier = "religion"
      name = "Religion"
      pre = "💀"
      url = "/factbook/society/culture/religion"
      parent = "culture"
      weight = 3
    [[navbar]]
      identifier = "sagas"
      name = "Sagas"
      pre = "🕯️"
      url = "/factbook/society/culture/sagas"
      parent = "culture"
      weight = 4
  [[navbar]]
    identifier = "landscape"
    name = "Landscape"
    pre = "🌿"
    parent = "factbook"
    url = "/factbook/landscape"
    weight = 5
    [[navbar]]
      identifier = "boroughs"
      name = "Boroughs"
      pre = "🌐"
      url = "/factbook/landscape/boroughs"
      parent = "landscape"
      weight = 1
  [[navbar]]
    identifier = "society"
    name = "Society"
    pre = "🏛"
    parent = "factbook"
    url = "/factbook/society"
    weight = 6
    [[navbar]]
      identifier = "state"
      name = "State"
      pre = "🌸"
      url = "/factbook/society/state/"
      parent = "society"
      weight = 1
    [[navbar]]
      identifier = "industry"
      name = "Industry"
      pre = "⚙️"
      url = "/factbook/society/industry/"
      parent = "society"
      weight = 2
    [[navbar]]
    identifier = "technology"
    name = "Technology"
    pre = "🧪"
    url = "/factbook/society/technology"
    parent = "society"
    weight = 3
  [[navbar]]
    identifier = "timeline"
    name = "Timeline"
    pre = "⏳"
    parent = "factbook"
    url = "/factbook/timeline"
    weight = 6
[[navbar]]
  identifier = "newsdesk"
  name = "MillMint"
  pre = "📕"
  url = "/millmint/"
  weight = 3
  [[navbar]]
    identifier = "about"
    name = "About"
    pre = "🌐"
    url = "/millmint/about"
    parent = "newsdesk"
    weight = 1
  [[navbar]]
    identifier = "dolls"
    name = "Dolls"
    pre = "🧍‍♀️"
    url = "/millmint/dolls/"
    parent = "newsdesk"
    weight = 2
  [[navbar]]
    identifier = "commissions"
    name = "Commissions"
    pre = "✏️"
    url = "/millmint/commissions"
    parent = "newsdesk"
    weight = 3
  [[navbar]]
    identifier = "essays"
    name = "Essays"
    pre = "📄"
    url = "/millmint/essays"
    parent = "newsdesk"
    weight = 4
    [[navbar]]
      identifier = "social-economy"
      name = "A Social Economy"
      pre = "💸"
      url = "/millmint/essays/social-economy"
      parent = "essays"
      weight = 1
    [[navbar]]
      identifier = "ghibli"
      name = "A Universal Nostalgia"
      pre = "🫧"
      url = "/millmint/essays/ghibli"
      parent = "essays"
      weight = 2
    [[navbar]]
      identifier = "utopie"
      name = "Utopie Concrete"
      pre = "☕️"
      url = "/millmint/essays/utopie"
      parent = "essays"
      weight = 3
    [[navbar]]
      identifier = "hong kong"
      name = "Not Long in Hong Kong"
      pre = "☂️"
      url = "/millmint/essays/hongkong"
      parent = "essays"
      weight = 4
    [[navbar]]
      identifier = "west"
      name = "The West Coast"
      pre = "🏔️"
      url = "/millmint/essays/west"
      parent = "essays"
      weight = 5
[[navbar]]
  identifier = "posts"
  name = "Stories"
  pre = "📗"
  url = "/stories/"
  weight = 4