[[navbar]]
  identifier = "intro"
  name = "Intro"
  url = "/intro/"
  pre = "📔"
  weight = 1
[[navbar]]
  identifier = "utopia"
  name = "Utopia"
  pre = "📓"
  url = "/utopia/"
  weight = 2
  [[navbar]]
    identifier = "vekllei"
    name = "Vekllei"
    pre = "🎋"
    url = "/utopia/vekllei/"
    parent = "utopia"
    weight = 1
  [[navbar]]
    identifier = "characters"
    name = "Characters"
    pre = "🎎"
    url = "/utopia/characters/"
    parent = "utopia"
    weight = 2
  [[navbar]]
    identifier = "culture"
    name = "Culture"
    pre = "🏵"
    url = "/utopia/culture"
    parent = "utopia"
    weight = 3
    [[navbar]]
      identifier = "language"
      name = "Language"
      pre = "📖"
      url = "/utopia/culture/language"
      parent = "culture"
      weight = 1
    [[navbar]]
      identifier = "metaphysics"
      name = "Metaphysics"
      pre = "🪬"
      url = "/utopia/culture/metaphysics"
      parent = "culture"
      weight = 2
    [[navbar]]
      identifier = "religion"
      name = "Religion"
      pre = "💀"
      url = "/utopia/culture/religion"
      parent = "culture"
      weight = 3
  [[navbar]]
    identifier = "landscape"
    name = "Landscape"
    pre = "🌿"
    parent = "utopia"
    url = "/utopia/landscape"
    weight = 4
    [[navbar]]
      identifier = "boroughs"
      name = "Boroughs"
      pre = "🌐"
      url = "/utopia/landscape/boroughs"
      parent = "landscape"
      weight = 1
  [[navbar]]
    identifier = "society"
    name = "Society"
    pre = "🏛"
    parent = "utopia"
    url = "/utopia/society"
    weight = 5
    [[navbar]]
      identifier = "state"
      name = "State"
      pre = "🌸"
      url = "/utopia/society/state/"
      parent = "society"
      weight = 1
    [[navbar]]
      identifier = "finance"
      name = "Finance"
      pre = "💵"
      url = "/utopia/society/state/finance/"
      parent = "society"
      weight = 2
    [[navbar]]
      identifier = "assets"
      name = "State Assets"
      pre = "🏬"
      url = "/utopia/society/state/assets"
      parent = "society"
      weight = 4
    [[navbar]]
      identifier = "computers"
      name = "Computers"
      pre = "🖥"
      url = "/utopia/society/technology/computers"
      parent = "society"
      weight = 5
    [[navbar]]
      identifier = "mail"
      name = "Mail"
      pre = "📯"
      url = "/utopia/society/industry/mail"
      parent = "society"
      weight = 6
    [[navbar]]
      identifier = "railways"
      name = "Railways"
      pre = "🚇"
      url = "/utopia/society/industry/rail"
      parent = "society"
      weight = 7
[[navbar]]
  identifier = "newsdesk"
  name = "News"
  pre = "📕"
  url = "/news/"
  weight = 3
  [[navbar]]
    identifier = "about"
    name = "About"
    pre = "❓"
    url = "/news/about"
    parent = "newsdesk"
    weight = 1
  [[navbar]]
    identifier = "blog"
    name = "Blog"
    pre = "💬"
    url = "/news/blog"
    parent = "newsdesk"
    weight = 2
  [[navbar]]
    identifier = "essays"
    name = "Essays"
    pre = "📄"
    url = "/news/essays"
    parent = "newsdesk"
    weight = 3
    [[navbar]]
      identifier = "ghibli"
      name = "A Universal Nostalgia"
      pre = "🫧"
      url = "/news/essays/ghibli"
      parent = "essays"
      weight = 1
    [[navbar]]
      identifier = "utopie"
      name = "Utopie Concrete"
      pre = "☕️"
      url = "/news/essays/utopie"
      parent = "essays"
      weight = 2
    [[navbar]]
      identifier = "hong kong"
      name = "Not Long in Hong Kong"
      pre = "☂️"
      url = "/news/essays/hongkong"
      parent = "essays"
      weight = 3
    [[navbar]]
      identifier = "tokyo"
      name = "A Cashless Tokyo"
      pre = "🍜"
      url = "/news/essays/tokyo"
      parent = "essays"
      weight = 4
[[navbar]]
  identifier = "posts"
  name = "Stories"
  pre = "📗"
  url = "/stories/"
  weight = 4