[[navbar]]
  identifier = "intro"
  name = "Intro"
  url = "/intro/"
  weight = 1
[[navbar]]
  identifier = "utopia"
  name = "Utopia"
  url = "/utopia/vekllei"
  weight = 2
  [[navbar]]
    identifier = "vekllei"
    name = "Vekllei"
    url = "/utopia/vekllei/"
    parent = "utopia"
    weight = 1
  [[navbar]]
    identifier = "characters"
    name = "Characters"
    url = "/utopia/characters/"
    parent = "utopia"
    weight = 2
  [[navbar]]
    identifier = "culture"
    name = "Culture"
    url = "/utopia/vekllei/culture"
    parent = "utopia"
    weight = 3
    [[navbar]]
      identifier = "language"
      name = "Language"
      url = "/utopia/vekllei/culture/language"
      parent = "culture"
      weight = 1
    [[navbar]]
      identifier = "religion"
      name = "Religion"
      url = "/utopia/vekllei/culture/religion"
      parent = "culture"
      weight = 2
  [[navbar]]
    identifier = "landscape"
    name = "Landscape"
    parent = "utopia"
    url = "/utopia/vekllei/landscape"
    weight = 4
    [[navbar]]
      identifier = "boroughs"
      name = "Boroughs"
      url = "/utopia/vekllei/landscape/boroughs"
      parent = "landscape"
      weight = 1
  [[navbar]]
    identifier = "society"
    name = "Society"
    parent = "utopia"
    url = "/utopia/vekllei/society"
    weight = 5
    [[navbar]]
      identifier = "mail"
      name = "Mail"
      url = "/utopia/vekllei/society/industry/mail"
      parent = "society"
      weight = 2
    [[navbar]]
      identifier = "railways"
      name = "Railways"
      url = "/utopia/vekllei/society/industry/rail"
      parent = "society"
      weight = 3
[[navbar]]
  identifier = "newsdesk"
  name = "News"
  url = "/news/"
  weight = 3
  [[navbar]]
    identifier = "about"
    name = "About"
    url = "/news/about"
    parent = "newsdesk"
    weight = 2
  [[navbar]]
    identifier = "bulletin"
    name = "Bulletin"
    url = "/news/bulletin"
    parent = "newsdesk"
    weight = 3
  [[navbar]]
    identifier = "essays"
    name = "Essays"
    url = "/news/essays"
    parent = "newsdesk"
    weight = 4
    [[navbar]]
      identifier = "ghibli"
      name = "A Universal Nostalgia"
      url = "/news/essays/ghibli"
      parent = "essays"
      weight = 1
    [[navbar]]
      identifier = "utopie"
      name = "Utopie Concrete"
      url = "/news/essays/utopie"
      parent = "essays"
      weight = 2
    [[navbar]]
      identifier = "hong kong"
      name = "Not Long in Hong Kong"
      url = "/news/essays/hongkong"
      parent = "essays"
      weight = 3
    [[navbar]]
      identifier = "tokyo"
      name = "A Cashless Tokyo"
      url = "/news/essays/tokyo"
      parent = "essays"
      weight = 4
[[navbar]]
  identifier = "posts"
  name = "Stories"
  url = "/posts/"
  weight = 4